export const FEATURE_REGISTRY=[
 {id:'discord-commands',name:'Slash Command Registry',category:'Discord',description:'Namespace slash command terdaftar untuk JKT48, game, simulasi, utility, economy, moderation, support, feed, media, verification, dan developer tools.',status:'active'},
 {id:'jkt48-members',name:'JKT48 Member Database',category:'JKT48',description:'Sinkronisasi member generasi 1-14 dari sumber JSON publik.',status:'active'},
 {id:'jkt48-upcoming',name:'JKT48 Upcoming',category:'JKT48',description:'Event, theater, setlist, songs, live, birthday, dan graduation.',status:'active'},
 {id:'jkt48-latest',name:'JKT48 Latest',category:'JKT48',description:'Data terbaru event, theater, setlist, songs, live, birthday, graduation, SHOWROOM, dan IDN.',status:'active'},
 {id:'jkt48-feed',name:'JKT48 Platform Feed',category:'Notification',description:'Feed publik untuk JKT48 Website, IDN, SHOWROOM, YouTube, Instagram, TikTok, X/Twitter, Threads, Tokopedia, Shopee, dan kanal costume.',status:'active'},
 {id:'jkt48-quiz',name:'JKT48 Quiz',category:'Game',description:'Mode quiz suara, foto member, setlist, lagu, dan random member.',status:'active'},
 {id:'jkt48-gacha',name:'JKT48 Gacha',category:'Game',description:'Gacha kartu dengan rarity Common hingga Secret dan database terpisah.',status:'active'},
 {id:'jkt48-cards',name:'JKT48 Card Collection',category:'Game',description:'Inventory dan statistik koleksi kartu.',status:'active'},
 {id:'streetview-quiz',name:'Google Street View Quiz',category:'Game',description:'Tebak lokasi dari foto Google Street View dengan rotasi heading dan FOV acak.',status:'active'},
 {id:'game-cooldown',name:'Game Cooldown',category:'Game',description:'Cooldown pemakaian game/gacha 10 detik per user dan server.',status:'active'},
 {id:'quiz-timeout',name:'Quiz Timeout',category:'Game',description:'Setiap tebak-tebakan memiliki batas jawaban 1 menit dan gagal otomatis bila timeout.',status:'active'},
 {id:'simulation',name:'Simulation Tycoon',category:'Game',description:'Profil kota, daily, bank, fishing, build, dan gacha.',status:'active'},
 {id:'economy',name:'Server Economy',category:'Community',description:'Saldo, daily reward, dan penyimpanan ekonomi per server/user.',status:'active'},
 {id:'leveling',name:'Leveling',category:'Community',description:'XP dan level berdasarkan aktivitas pesan.',status:'active'},
 {id:'moderation',name:'Moderation',category:'Security',description:'Warning, ban, anti-spam, anti-invite, link moderation, dan timeout.',status:'active'},
 {id:'tickets',name:'Support Tickets',category:'Support',description:'Ticket privat dengan role staff dan tombol close.',status:'active'},
 {id:'welcome-goodbye',name:'Welcome / Goodbye',category:'Community',description:'Pesan otomatis saat member masuk atau keluar.',status:'active'},
 {id:'guild-invite-welcome',name:'Guild Invite Welcome',category:'Community',description:'Pesan otomatis sekali saat bot berhasil diundang ke server baru.',status:'active'},
 {id:'help-command',name:'Help Command',category:'Discord',description:'Katalog semua fitur dan command dalam embed dengan filter kategori dan pagination.',status:'active'},
 {id:'setup-command',name:'Setup Command',category:'Discord',description:'Ringkasan dan konfigurasi welcome, log, scraper, Ramadan, disaster, dan fitur server lainnya. Owner bot only.',status:'active'},
 {id:'settingbot-command',name:'Setting Bot Command',category:'Developer',description:'Pengaturan global bot seperti maintenance dan activity, khusus owner bot.',status:'active'},
 {id:'blacklist-server',name:'Server Blacklist',category:'Security',description:'Blacklist server global dan otomatis meninggalkan server yang diblacklist.',status:'active'},
 {id:'blacklist-user',name:'User Blacklist',category:'Security',description:'Blacklist user global untuk mencegah penggunaan bot.',status:'active'},
 {id:'electronics-prices',name:'Electronics Prices',category:'Indonesia',description:'Scraper harga elektronik publik dengan kategori smartphone, laptop, tablet, TV, audio, kamera, gaming, storage, dan lainnya.',status:'active'},
 {id:'media-download',name:'Media Downloader',category:'Media',description:'Download video, audio, dan image dari sumber publik melalui yt-dlp/direct metadata.',status:'active'},
 {id:'media-resolution',name:'Media Resolution',category:'Media',description:'Pilihan resolusi video dari 360p sampai 2160p/best sesuai sumber.',status:'active'},
 {id:'media-vocals',name:'Vocal Separation',category:'Media',description:'Pemisahan vocal dan instrumental dengan Demucs.',status:'active'},
 {id:'media-background',name:'Background Removal',category:'Media',description:'Penghapusan background image/video dengan rembg.',status:'active'},
 {id:'media-watermark',name:'Watermark Removal',category:'Media',description:'Inpainting watermark pada area koordinat yang diberikan.',status:'active'},
 {id:'media-settings',name:'Media User Settings',category:'Media',description:'Default resolusi dan format media per user.',status:'active'},
 {id:'verification-web',name:'Web Verification',category:'Security',description:'Website verifikasi dengan checkbox I\'m not a robot, ticket sesi, kode sekali pakai, dan expiry.',status:'active'},
 {id:'verification-server-code',name:'Server-bound Verification Code',category:'Security',description:'Kode 4 karakter yang diturunkan dari secret unik setiap server Discord dan nonce sesi.',status:'active'},
 {id:'verification-role',name:'Verification Role',category:'Security',description:'Role Discord opsional yang diberikan setelah kode valid ditukarkan.',status:'active'},
 {id:'verification-rate-limit',name:'Verification Rate Limit',category:'Security',description:'Batas percobaan kode dan expiry untuk mengurangi brute force.',status:'active'},
 {id:'verification-api',name:'Verification Developer API',category:'Developer',description:'Endpoint health dan feature discovery untuk monitoring/developer tooling.',status:'active'},
 {id:'security-docs',name:'Security Policy',category:'Developer',description:'SECURITY.md berisi pelaporan vulnerability dan praktik pengamanan secret.',status:'active'},
 {id:'feature-registry',name:'Feature Registry',category:'Developer',description:'Registry terpusat agar command, dokumentasi, dan website membaca daftar fitur dari sumber yang sama.',status:'active'},
 {id:'bot-info',name:'Bot Info',category:'Developer',description:'Informasi runtime, versi, guild count, dan runtime environment.',status:'active'},
 {id:'bot-features',name:'Bot Feature Catalog',category:'Developer',description:'Menampilkan registry fitur aktif dari bot.',status:'active'},
 {id:'bot-health',name:'Bot Health',category:'Developer',description:'Status uptime, memory, database, dan verification web server.',status:'active'},
 {id:'indonesia-news',name:'Indonesia News',category:'Indonesia',description:'Berita Indonesia dari RSS ANTARA dengan kategori nasional, ekonomi, bisnis, bursa, politik, dan hukum.',status:'active'},
 {id:'indonesia-stocks',name:'Indonesia Stock Quotes',category:'Indonesia',description:'Quote saham IDX dan alias IHSG melalui ticker .JK dengan cache.',status:'active'},
 {id:'fuel-prices',name:'Fuel Prices',category:'Indonesia',description:'Data acuan harga BBM Pertamina dengan cache 24 jam dan sumber resmi/terkait.',status:'active'},
 {id:'electricity-prices',name:'Electricity Tariffs',category:'Indonesia',description:'Ringkasan tarif listrik menurut golongan pelanggan dengan cache 24 jam.',status:'active'},
 {id:'food-prices',name:'Food Prices',category:'Indonesia',description:'Harga pangan strategis dan komoditas utama dengan cache 24 jam.',status:'active'},
 {id:'ramadan-calendar',name:'Upcoming Ramadan',category:'Ramadan',description:'Informasi perkiraan Ramadan, Nuzulul Quran, akhir Ramadan dan status penetapan.',status:'active'},
 {id:'imsakiyah',name:'Imsakiyah Schedule',category:'Ramadan',description:'Jadwal imsak, subuh, maghrib, dan sholat berdasarkan kota.',status:'active'},
 {id:'sahur-notification',name:'Sahur Notification',category:'Ramadan',description:'Notifikasi sahur 30 menit sebelum imsak ke channel server.',status:'active'},
 {id:'iftar-notification',name:'Iftar Notification',category:'Ramadan',description:'Notifikasi berbuka saat waktu maghrib.',status:'active'},
 {id:'indonesia-data-refresh',name:'Indonesia Data Refresh',category:'Developer',description:'Refresh terjadwal untuk cache berita dan data publik Indonesia.',status:'active'},
 {id:'scraper-registry',name:'Scraper Registry',category:'Developer',description:'Registry sumber URL dan adapter untuk data eksternal non-JKT48.',status:'active'},
 {id:'url-health-check',name:'URL Health Check',category:'Developer',description:'Pemeriksaan kesehatan URL scraper setiap 10 detik.',status:'active'},
 {id:'database-audit',name:'Database Data Audit',category:'Developer',description:'Audit seluruh database bot, kolom URL, status sumber, dan error data.',status:'active'},
 {id:'scraper-method-suggestion',name:'Scraper Method Suggestion',category:'Developer',description:'Menyarankan metode JSON, RSS/XML, media, API, atau HTML ketika URL belum punya adapter.',status:'active'},
 {id:'disaster-monitor',name:'Disaster Monitor',category:'Security',description:'Monitoring gempa, tsunami, gunung api, dan kejadian bencana umum dari sumber resmi.',status:'active'},
 {id:'disaster-notification',name:'Disaster Notification',category:'Security',description:'Notifikasi kejadian baru dengan lokasi dan sumber ke channel server.',status:'active'},
 {id:'system-status',name:'System Status',category:'Developer',description:'Slash command untuk runtime, database, scraper, audit, source, dan disaster status.',status:'active'}
];

export function getFeatures({category}={}){
 const rows=category?FEATURE_REGISTRY.filter(x=>x.category.toLowerCase()===String(category).toLowerCase()):FEATURE_REGISTRY;
 return [...rows];
}
